version: 2

project_name: wheatley

before:
  hooks:
    - go mod tidy
builds:
  - id: wheatley
    main: ./cmd/
    binary: wheatley
    ldflags:
      - -X main.version={{.Env.VERSION}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds:
      - wheatley
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - .env.example
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  use: github-native
  abbrev: 0
  sort: asc
